# Run the quarto static site generation and upload to GCS

steps:
  - name: python:3.10
    entrypoint: sh
    args: |
      - "-c"
      - |
        set -ux
        python -m pip install --upgrade pip
        pip install -Uq nbdev
        test -f setup.py && pip install -e ".[dev]" --extra-index-url https://download.pytorch.org/whl/cpu
        nbdev_docs

    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: 'gsutil'
      args:
        - cp
        - -r
        - ./_docs
        - gs://slowai