# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/slowai',
                'doc_host': 'https://jeremy.github.io',
                'git_url': 'https://github.com/jeremy/slowai',
                'lib_path': 'slowai'},
  'syms': {'slowai.core': {'slowai.core.foo': ('core.html#foo', 'slowai/core.py')}}}
