# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/12a_augmentation_with_normalization.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/12a_augmentation_with_normalization.ipynb 2
import torch
from torchvision import transforms

from slowai.learner import (
    DataLoaders,
    tensorize_images,
)
from .augmentation import ResNetWithGlobalPoolingInitialConv, summarize, train
