# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_calculus.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03_calculus.ipynb 3
from dataclasses import dataclass
from typing import Any

import lightning as L
import matplotlib.pyplot as plt
import numpy as np
import sympy
import torch
import torch.nn.functional as F
import torchvision
import torchvision.transforms as transforms
from einops import rearrange
from torch import nn
from torch.utils.data import DataLoader

from .overview import show_image
