# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/26_colorization.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/26_colorization.ipynb 2
from functools import partial

import torch
import torch.nn.functional as F
from torch.optim import AdamW, lr_scheduler
from torchmetrics.classification import MulticlassAccuracy

from .coco import get_coco_dataset_super_rez, get_coco_dataset_colorization
from .convs import def_device
from .ddpm import AccelerateCB
from slowai.learner import (
    Callback,
    DataLoaders,
    DeviceCB,
    MetricsCB,
    ProgressCB,
    TrainLearner,
)
from .sgd import BatchSchedulerCB
from .super_rez import TinyUnetWithCrossConvolutions as Unet
from .super_rez import train, viz
from .tinyimagenet_a import denorm, lr_find
from .utils import show_image, show_images
