# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_autoencoders.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/07_autoencoders.ipynb 2
from typing import Mapping

import fastcore.all as fc
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn.functional as F
import torchvision.transforms.functional as T
from datasets import load_dataset
from torch import nn, optim, tensor
from torch.utils.data import DataLoader, default_collate

from .convs import get_dls_from_dataset_dict, conv
from .datasets import show_image, show_images
