# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/13_ddpm.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/13_ddpm.ipynb 3
import random
import re
from contextlib import contextmanager
from math import sqrt
from typing import Sequence

import matplotlib.pyplot as plt
import numpy as np
import timm
import torch
import torch.nn.functional as F
from diffusers import LMSDiscreteScheduler
from einops import rearrange
from IPython.display import Markdown, display
from torch import distributions, nn
from torch.nn import init
from torch.optim import lr_scheduler
from torchmetrics.classification import MulticlassAccuracy
from torchvision import transforms

from .activations import StoreModuleStatsCB, set_seed
from .augmentation import train
from .initializations import init_leaky_weights, set_seed
from slowai.learner import (
    DeviceCB,
    Learner,
    MetricsCB,
    ProgressCB,
    TrainCB,
    TrainLearner,
    after,
    batchify,
    def_device,
    fashion_mnist,
)
from .resnets import Conv, ResidualConvBlock
from .sgd import BatchSchedulerCB
from .utils import show_images
