# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_minibatch_training.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/04_minibatch_training.ipynb 3
import torch
import torch.nn.functional as F
from einops import rearrange

from .calculus import MNISTDataModule
