name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: settings.ini
      - name: Install Dependencies
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          pip install -Uq nbdev
          test -f setup.py && pip install -e ".[dev]" --extra-index-url https://download.pytorch.org/whl/cpu
          nbdev_docs
      - name: Commit docs directory
        shell: bash
        run: |
          set -ux

          if [[ -z $(git status -s) ]]; then
            echo "No changes to the docs directory. Exiting."
            exit 0
          fi

          git config --global user.name "GitHub Actions"
          git config --global user.email ""

          git add ./_docs
          git commit -m "Update docs"
          git push
